/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module mojo_top_0 (
    input clk,
    input rst_n,
    output reg [7:0] led,
    input cclk,
    output reg spi_miso,
    input spi_ss,
    input spi_mosi,
    input spi_sck,
    output reg [3:0] spi_channel,
    input avr_tx,
    output reg avr_rx,
    input avr_rx_busy,
    output reg [23:0] io_led,
    output reg [7:0] io_seg,
    output reg [3:0] io_sel,
    input [4:0] io_button,
    input [23:0] io_dip
  );
  
  
  
  reg rst;
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_1 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  
  wire [16-1:0] M_alu_out;
  reg [16-1:0] M_alu_a;
  reg [16-1:0] M_alu_b;
  reg [6-1:0] M_alu_alufn;
  alu16_2 alu (
    .a(M_alu_a),
    .b(M_alu_b),
    .alufn(M_alu_alufn),
    .out(M_alu_out)
  );
  
  wire [16-1:0] M_test_a_out;
  wire [16-1:0] M_test_b_out;
  wire [1-1:0] M_test_out;
  reg [6-1:0] M_test_alufn;
  reg [16-1:0] M_test_b_dip;
  reg [16-1:0] M_test_alu_out;
  tester_3 test (
    .alufn(M_test_alufn),
    .b_dip(M_test_b_dip),
    .alu_out(M_test_alu_out),
    .a_out(M_test_a_out),
    .b_out(M_test_b_out),
    .out(M_test_out)
  );
  
  always @* begin
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    led = 8'h00;
    spi_miso = 1'bz;
    spi_channel = 4'bzzzz;
    avr_rx = 1'bz;
    io_led = 24'h000000;
    io_seg = 8'hff;
    io_sel = 4'hf;
    M_test_alufn = io_dip[16+2+5-:6];
    M_alu_alufn = io_dip[16+2+5-:6];
    M_alu_a = M_test_a_out;
    M_alu_b = M_test_b_out;
    M_test_b_dip[8+7-:8] = io_dip[8+7-:8];
    M_test_b_dip[0+7-:8] = io_dip[0+7-:8];
    M_test_alu_out = M_alu_out;
    io_led[0+7-:8] = M_alu_out[0+7-:8];
    io_led[8+7-:8] = M_alu_out[8+7-:8];
    io_led[16+7-:8] = {4'h8{M_test_out}};
  end
endmodule
