/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module tester_3 (
    input [5:0] alufn,
    input [15:0] b_dip,
    input [15:0] alu_out,
    output reg [15:0] a_out,
    output reg [15:0] b_out,
    output reg out
  );
  
  
  
  reg [15:0] a;
  
  reg [15:0] b;
  
  reg [15:0] add_ans;
  
  reg [15:0] sub_ans;
  
  reg [15:0] mult_ans;
  
  reg [15:0] shl_ans;
  
  reg [15:0] shr_ans;
  
  reg [15:0] sra_ans;
  
  always @* begin
    a = 16'hfcb8;
    b = b_dip[0+15-:16];
    add_ans = a + b;
    sub_ans = a - b;
    mult_ans = a * b;
    shl_ans = a << b;
    shr_ans = a >> b;
    sra_ans = $signed(a) >>> b;
    out = 1'h0;
    a_out = a;
    b_out = b;
    
    case (alufn)
      6'h00: begin
        out = (alu_out == add_ans);
      end
      6'h01: begin
        out = (alu_out == sub_ans);
      end
      6'h02: begin
        out = (alu_out == mult_ans);
      end
      6'h3f: begin
        out = (alu_out == (a + b));
      end
      6'h20: begin
        out = (alu_out == shl_ans);
      end
      6'h21: begin
        out = (alu_out == shr_ans);
      end
      6'h23: begin
        out = (alu_out == sra_ans);
      end
      6'h18: begin
        out = (alu_out == (a & b));
      end
      6'h1e: begin
        out = (alu_out == (a | b));
      end
      6'h16: begin
        out = (alu_out == (a ^ b));
      end
      6'h1a: begin
        out = (alu_out == a);
      end
      6'h33: begin
        out = (alu_out == (a == b));
      end
      6'h35: begin
        out = (alu_out == (a < b));
      end
      6'h37: begin
        out = (alu_out == (a <= b));
      end
    endcase
  end
endmodule
